/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mega.sdk;

public class MegaLogger {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MegaLogger(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MegaLogger obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        megaJNI.delete_MegaLogger(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    megaJNI.MegaLogger_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    megaJNI.MegaLogger_change_ownership(this, swigCPtr, true);
  }

  public void log(String time, int loglevel, String source, String message) {
    if (getClass() == MegaLogger.class) megaJNI.MegaLogger_log(swigCPtr, this, time, loglevel, source, message); else megaJNI.MegaLogger_logSwigExplicitMegaLogger(swigCPtr, this, time, loglevel, source, message);
  }

  public MegaLogger() {
    this(megaJNI.new_MegaLogger(), true);
    megaJNI.MegaLogger_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
