'''
Usage:
This command must have 1 parameter of csv format coverage report generated by JaCoCO
    python3 coverage_report.py ${WORKSPACE}/domain/build/reports/jacoco/test/jacocoTestReport.csv

Output example:
1.20%=2079/173673

Exclusions (generated code, test classes, etc.) are applied when the JaCoCo report is
generated - see the Jacoco convention plugins in build-logic/convention - so every row
in the CSV counts towards the coverage.
'''

import os
import sys

if len(sys.argv) < 2:
    print("[ERROR] Coverage parameter missing. Coverage report is needed!")
    exit(0)

coverage_csv_file = sys.argv[1]
if not os.path.exists(coverage_csv_file):
    print("Internal error, Coverage Report file does not exist!")
    exit(0)

total_covered_lines = 0
total_lines = 0

with open(coverage_csv_file, 'r') as file_handle:
    for line in file_handle.readlines()[1:]:
        values = line.split(",")
        line_missed = int(values[7])
        line_covered = int(values[8])
        total_covered_lines += line_covered
        total_lines += line_covered + line_missed

# This outputs a String in this format:
# 1.20%=2079/173673
if total_lines != 0:
    print("{:.2f}%={}/{}".format(float(total_covered_lines)/float(total_lines) * 100, total_covered_lines, total_lines))
else:
    print("0.00%={}/{}".format(0, 0))
