#ifndef __LIBWS_PRIVATE_CONFIG_H__
#define __LIBWS_PRIVATE_CONFIG_H__

#define LIBWS_HAVE_UNISTD_H
#define LIBWS_HAVE_SYS_TIME_H
#define LIBWS_HAVE_SYS_SOCKET_H
#define LIBWS_HAVE_STDINT_H
#define LIBWS_HAVE_INTTYPES_H
#define LIBWS_HAVE_SYS_TYPES_H

#endif // __LIBWS_PRIVATE_CONFIG_H__
