[versions]
firebase-crashlytics = "3.0.7"
firebase-performance = "2.0.2"
firebase-app-distribution = "5.3.0"
gradle = "9.2.1"
google-services = "4.5.0"
hilt = "2.60.1"
jacoco = "0.8.15"
jfrog = "6.0.4"
kotlin = "2.4.0"
navigation = "2.10.0-alpha06"
ksp = "2.3.7"
megagradle = "0.88.20260519024856"
jfrog-artifactory = "6.0.4"
serialisation = "2.4.0"
benchmark-baseline-profile = "1.5.0-alpha07"
compose-screenshot = "0.0.1-alpha15"

[libraries]
build-tools = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebase-crashlytics" }
firebase-performance = { module = "com.google.firebase:perf-plugin", version.ref = "firebase-performance" }
firebase-app-distribution = { module = "com.google.firebase:firebase-appdistribution-gradle", version.ref = "firebase-app-distribution" }
google-services = { module = "com.google.gms:google-services", version.ref = "google-services" }
hilt-android = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
jacoco = { module = "org.jacoco:org.jacoco.core", version.ref = "jacoco" }
jfrog = { module = "org.jfrog.buildinfo:build-info-extractor-gradle", version.ref = "jfrog" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
navigation-safeargs = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation" }
ksp-gradle-plugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
benchmark-baseline-profile = { module = "androidx.benchmark:benchmark-baseline-profile-gradle-plugin", version.ref = "benchmark-baseline-profile" }

[plugins]
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
jfrog-artifactory = { id = "com.jfrog.artifactory", version.ref = "jfrog-artifactory" }
mega-artifactory-publish-convention = { id = "mega.artifactory.publish.convention", version.ref = "megagradle" }
mega-android-release = { id = "mega.android.release", version.ref = "megagradle" }
mega-android-cicd = { id = "mega.android.cicd", version.ref = "megagradle" }
kotlin-serialisation = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialisation"}
compose-screenshot = { id = "com.android.compose.screenshot", version.ref = "compose-screenshot" }
