package mega.privacy.android.navigation.destination

import androidx.navigation3.runtime.NavKey
import kotlinx.serialization.Serializable


/**
 * Navigation key for SaveScannedDocumentsScreen
 *
 * @param originatedFromChat True if the scan originated from chat
 * @param cloudDriveParentHandle The parent handle used when saving to Cloud Drive
 * @param scanPdfUri String representation of the PDF Uri generated by the scanner
 * @param scanSoloImageUri String representation of the single image Uri if available
 */
@Serializable
data class SaveScannedDocumentsNavKey(
    val originatedFromChat: Boolean = false,
    val cloudDriveParentHandle: Long? = null,
    val scanPdfUri: String,
    val scanSoloImageUri: String? = null,
) : NavKey