package mega.privacy.android.app.constants

object EventConstants {
    const val EVENT_TEXT_FILE_UPLOADED = "EVENT_TEXT_FILE_UPLOADED"
    const val EVENT_REFRESH = "EVENT_REFRESH"
    const val EVENT_FINISH_ACTIVITY = "EVENT_FINISH_ACTIVITY"
    const val EVENT_SHOW_REMOVE_PHONE_NUMBER_CONFIRMATION = "EVENT_SHOW_REMOVE_PHONE_NUMBER_CONFIRMATION"
    const val EVENT_USER_NAME_UPDATED = "EVENT_USER_NAME_UPDATED"
    const val EVENT_USER_EMAIL_UPDATED = "EVENT_USER_EMAIL_UPDATED"
}