package mega.privacy.android.app.constants

object EventConstants {
    const val EVENT_TEXT_FILE_UPLOADED = "EVENT_TEXT_FILE_UPLOADED"
    const val EVENT_REFRESH = "EVENT_REFRESH"
    const val EVENT_FINISH_ACTIVITY = "EVENT_FINISH_ACTIVITY"
    const val EVENT_USER_NAME_UPDATED = "EVENT_USER_NAME_UPDATED"
    const val EVENT_USER_EMAIL_UPDATED = "EVENT_USER_EMAIL_UPDATED"
    const val EVENT_PERFORM_SCROLL = "EVENT_PERFORM_SCROLL"
    const val EVENT_REFRESH_PHONE_NUMBER = "EVENT_REFRESH_PHONE_NUMBER"
    const val EVENT_PURCHASES_UPDATED = "EVENT_PURCHASES_UPDATED"
    const val EVENT_2FA_UPDATED = "EVENT_2FA_UPDATED"
    const val EVENT_SHOW_SCANNING_FOLDER_DIALOG = "EVENT_SHOW_SCANNING_FOLDER_DIALOG"
}